/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Items CRUD API
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Item,
  ItemListResponse
} from '../itemsCRUDAPI.schemas';


export const getListItemsResponseMock = (overrideResponse: Partial<Extract<ItemListResponse, object>> = {}): ItemListResponse => ({items: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z'})), total: faker.number.int(), page: faker.number.int(), limit: faker.number.int(), ...overrideResponse})

export const getCreateItemResponseMock = (overrideResponse: Partial<Extract<Item, object>> = {}): Item => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getGetItemResponseMock = (overrideResponse: Partial<Extract<Item, object>> = {}): Item => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})

export const getUpdateItemResponseMock = (overrideResponse: Partial<Extract<Item, object>> = {}): Item => ({id: faker.string.uuid(), name: faker.string.alpha({length: {min: 10, max: 20}}), description: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), null]), undefined]), created_at: faker.date.past().toISOString().slice(0, 19) + 'Z', ...overrideResponse})


export const getListItemsMockHandler = (overrideResponse?: ItemListResponse | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ItemListResponse> | ItemListResponse), options?: RequestHandlerOptions) => {
  return http.get('*/v1/items', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListItemsResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateItemMockHandler = (overrideResponse?: Item | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Item> | Item), options?: RequestHandlerOptions) => {
  return http.post('*/v1/items', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateItemResponseMock(),
      { status: 201
      })
  }, options)
}

export const getGetItemMockHandler = (overrideResponse?: Item | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Item> | Item), options?: RequestHandlerOptions) => {
  return http.get('*/v1/items/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetItemResponseMock(),
      { status: 200
      })
  }, options)
}

export const getUpdateItemMockHandler = (overrideResponse?: Item | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<Item> | Item), options?: RequestHandlerOptions) => {
  return http.put('*/v1/items/:id', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
  
  
    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateItemResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteItemMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/v1/items/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
  
    return new HttpResponse(null,
      { status: 204
      })
  }, options)
}
export const getItemsMock = () => [
  getListItemsMockHandler(),
  getCreateItemMockHandler(),
  getGetItemMockHandler(),
  getUpdateItemMockHandler(),
  getDeleteItemMockHandler()
]
