/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Items CRUD API
 * OpenAPI spec version: 1.0.0
 */
export interface Item {
  id: string;
  name: string;
  /** @nullable */
  description?: string | null;
  created_at: string;
}

export interface ItemListResponse {
  items: Item[];
  total: number;
  page: number;
  limit: number;
}

export interface CreateItemBody {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * @maxLength 1000
   * @nullable
   */
  description?: string | null;
}

export interface UpdateItemBody {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /**
   * @maxLength 1000
   * @nullable
   */
  description?: string | null;
}

export interface ErrorResponse {
  message: string;
}

export interface ValidationError {
  field: string;
  message: string;
}

export interface ValidationErrorResponse {
  message: string;
  errors: ValidationError[];
}

export type ListItemsParams = {
page?: number;
limit?: number;
sort?: ListItemsSort;
order?: ListItemsOrder;
search?: string;
};

export type ListItemsSort = typeof ListItemsSort[keyof typeof ListItemsSort];


export const ListItemsSort = {
  name: 'name',
  createdAt: 'createdAt',
} as const;

export type ListItemsOrder = typeof ListItemsOrder[keyof typeof ListItemsOrder];


export const ListItemsOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

